name: 'Dump Charm CI Log Artifacts'
description: 'Dumps to Artifacts useful Juju, Kubernetes, and Charmcraft log information.  Requires kubectl to be set up with a context, and charmcraft to be installed.'
runs:
  using: 'composite'
  steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Create artifact collection directory
      id: mkdir
      shell: bash
      if: always()
      run: |
        LOG_DIR="tmp_logs"
        echo "log-dir=$(echo $LOG_DIR)" >> $GITHUB_OUTPUT
        mkdir $LOG_DIR

    # Charmcraft

    - name: Collect charmcraft logs
      shell: bash
      if: always()
      # Use grep as cat will fail if no logs exist
      run: |
        grep -hs ^ /home/runner/snap/charmcraft/common/cache/charmcraft/log/charmcraft-*.log | tee ${{ steps.mkdir.outputs.log-dir }}/charmcraft_logs
        cp /home/runner/snap/charmcraft/common/cache/charmcraft/log/charmcraft-*.log ${{ steps.mkdir.outputs.log-dir }}/

    # Juju

    - name: 'Install juju-crashdump'
      shell: bash
      if: always()
      run: sudo snap install juju-crashdump

    - name: Collect juju-crashdump
      # Includes juju status, all debug-logs, model settings
      shell: bash
      if: always()
      run: juju-crashdump -o ${{ steps.mkdir.outputs.log-dir }}

    - name: Collect Juju status log
      shell: bash
      if: always()
      run: bash ${{ github.action_path }}/show-all-status-log.bash 2>&1 | tee ${{ steps.mkdir.outputs.log-dir }}/juju-status-logs.txt

    # Kubernetes

    - name: Collect kubectl cluster-info dump
      # Includes container logs, other details about basic k8s resources
      shell: bash
      if: always()
      run: |
        kubectl cluster-info dump | tee ${{ steps.mkdir.outputs.log-dir }}/kubectl-cluster-info-dump.txt

    - name: 'Install ketall'
      # https://github.com/corneliusweig/ketall
      shell: bash
      if: always()
      run: |
        wget https://github.com/corneliusweig/ketall/releases/download/v1.3.8/get-all-amd64-linux.tar.gz
        tar -xf get-all-amd64-linux.tar.gz
        mv get-all-amd64-linux ketall

    - name: Collect deeper Kubernetes resource details
      # Includes CRDs, full yaml definitions
      shell: bash
      if: always()
      run: |
        ./ketall > ${{ steps.mkdir.outputs.log-dir }}/kubernetes-ketall.txt
        ./ketall -o yaml > ${{ steps.mkdir.outputs.log-dir }}/kubernetes-ketall-detailed.yaml

    - name: Upload debug artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: juju-kubernetes-charmcraft-logs
        path: ${{ steps.mkdir.outputs.log-dir }}
        if-no-files-found: error

