# Shows the github context of an action

name: Using Github Actions Cache
on: 
  pull_request:
    branches: [master]

jobs:
  dump_context:
    runs-on: ubuntu-latest
    env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: Dump GitHub context
        run: echo "$GITHUB_CONTEXT"

  without_cache:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Python dependencies
      run: |
        pip3 install tensorflow

  with_cache:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    # This works on ubuntu.  More advanced versions for multi-OS available here:
    # https://github.com/actions/cache/blob/main/examples.md#python---pip
    - name: pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-cache  # Demo hashes by requirements.txt, but why?

    - name: Install Python dependencies
      run: |
        pip3 install tensorflow
