name: Demo using default values in github expressions
on: 
  push:

jobs:
  show_default_values:
    runs-on: ubuntu-latest
    env:
          GLOBAL_SECRET_EXISTS: ${{ secrets.SECRET_THAT_EXISTS || secrets.SECRET_THAT_EXISTS_2 }}
          GLOBAL_SECRET_EXISTS_2: ${{ secrets.SECRET_THAT_DOESNT_EXIST || secrets.SECRET_THAT_EXISTS_2 }}
          GLOBAL_SECRET_DOESNT_EXIST: ${{ secrets.SECRET_THAT_DOESNT_EXIST || secrets.ANOTHER_SECRET_THAT_DOESNT_EXIST }}
    steps:
      - name: Dump GitHub context
        run: |
          echo "LOCAL_SECRET_EXISTS = $GLOBAL_SECRET_EXISTS"
          echo "GLOBAL_SECRET_EXISTS = $GLOBAL_SECRET_EXISTS"
          echo
          echo "LOCAL_SECRET_EXISTS_2 = $GLOBAL_SECRET_EXISTS_2"
          echo "GLOBAL_SECRET_EXISTS_2 = $GLOBAL_SECRET_EXISTS_2"
          echo
          echo "LOCAL_SECRET_DOESNT_EXIST = $GLOBAL_SECRET_DOESNT_EXIST"
          echo "GLOBAL_SECRET_DOESNT_EXIST = $GLOBAL_SECRET_DOESNT_EXIST"
          echo
        env:
              LOCAL_SECRET_EXISTS: ${{ secrets.SECRET_THAT_EXISTS || secrets.SECRET_THAT_EXISTS_2 }}
              LOCAL_SECRET_EXISTS_2: ${{ secrets.SECRET_THAT_DOESNT_EXIST || secrets.SECRET_THAT_EXISTS_2 }}
              LOCAL_SECRET_DOESNT_EXIST: ${{ secrets.SECRET_THAT_DOESNT_EXIST || secrets.ANOTHER_SECRET_THAT_DOESNT_EXIST }}
