# Handler of repository_dispatch events (events from external sources)

name: Receive Repository Dispatch Payload
# The pipeline is triggered on:
#  - Repository Dispatch
on: repository_dispatch

jobs:
  process-repository-dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      run: echo "${{ toJson(github) }}"
      
    - name: Copy Repository Contents
      uses: actions/checkout@master

    - name: Handle Repo Dispatch Payload
      id: rd
      run: |
        echo event_type = "${{ github.event.action }}"
        echo event.client_payload = "${{ toJson(github.event.client_payload) }}"

    - name: Handle Different Repo Dispatch Event
      id: rd_2
      if: github.event.action == 'my_print_comment_dispatch_event'
      run: |
        echo event.client_payload.comment = "${{ github.event.client_payload.comment }}"
