# Handler of repository_dispatch events (events from external sources)
# Uses dispatcher code from the PR rather than master (lets you develop
# the dispatcher).  Could use master by removing PR ref creation steps
name: Receive Repository Dispatch Payload
# The pipeline is triggered on:
#  - Repository Dispatch
on: repository_dispatch

jobs:
  process-repository-dispatch-via-python:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      run: echo "${{ toJson(github) }}"

    - name: Get associated event ref
      id: get_event_ref
      run: |
        event_ref="+refs/pull/${{ github.event.client_payload.pr_num }}/merge"
        echo "Writing $event_ref as output"
        echo "::set-output name=event_ref::$event_ref"

    - name: Copy Repository Contents
      uses: actions/checkout@v2
      with:
        # I think this is equivalent to doing 
        #   git fetch origin ${{ ...event_ref }}
        #   git checkout FETCH_HEAD
        ref: ${{ steps.get_event_ref.outputs.event_ref }}
      env:
        REPO: ${{ github.repository }}
        PR_NUM: ${{ steps.get_event_ref.outputs.pr_number }}

#     This example is from https://github.com/kaizentm/kubemlops
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Python dependencies
      run: |
        pip3 install requests --upgrade
    - name: Handle Repo Dispatch Payload
      id: rd
      run: |
        python3 event_dispatcher.py --event_type "${{ github.event.action }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # This example was taken from a Kubeflow Pipelines example
#         KFP_DSHB: ${{ secrets.KFP_DSHB }}
        KFP_DSHB: https://kubeflow.covid.cloud.statcan.ca/ 
      working-directory: .github/events
