# Replaces snap with something that'll fail sometimes, then shows it happened
name: Faily snap
on: 
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  work_always:
    runs-on: ubuntu-latest
    steps:
      - name: Install something successfully
        run: sudo snap install yq
  work_never:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: archive snap
        run: sudo mv /usr/bin/snap /usr/bin/snap_real
      - name: Replace snap with a flaky version
        run: sudo mv .github/workflows/faily_snap.sh /usr/bin/snap
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq
      - name: Do something in snap that is occasionally successful
        run: sudo snap info yq

