name: Test javascript actions
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
  issue_comment:
    types: [created]

jobs:
  test_pr_comment_context:
    runs-on: ubuntu-latest
    name: Testing PR Comment Context
    outputs:
      pr_number: ${{ steps.comment_context.outputs.pr_number }}
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./get-pr-comment-context/ # Uses an action in this directory
        id: comment_context
        with:
          allowed_author_associations: '[OWNER, COLLABORATOR]'
      - name: Get allowed_author
        run: echo "The value of allowed_author is ${{ steps.comment_context.outputs.allowed_author }}"
      - name: Get is_pr_comment
        run: echo "The value of is_pr_comment is ${{ steps.comment_context.outputs.is_pr_comment }}"
      - name: Get pr_number
        run: echo "The value of pr_number is ${{ steps.comment_context.outputs.pr_number }}"
      - name: Get from_pr_originator
        run: echo "The value of from_pr_originator is ${{ steps.comment_context.outputs.from_pr_originator }}"
  test_event_ref:
    runs-on: ubuntu-latest
    name: Testing Get Event Ref on PR
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./get-event-ref-on-pr/
        id: event_ref
      - name: Get event_ref
        run: echo "The value of event_ref (from custom event_ref grabber) is ${{ steps.event_ref.outputs.event_ref }} (vs ${{ github.ref}})"
  test_get_pr_branch_name:
    needs: test_pr_comment_context
    runs-on: ubuntu-latest
    name: Testing Getting Branch Name of PR
    steps:
      - uses: ./get-branch-name-of-pr/
        id: get-branch-name-of-pr
        with: 
          owner: 'ca-scribner'
          repository: 'github-actions-recipes'
          pr_number: ${{ needs.test_pr_comment_context.outputs.pr_number }}
      - name: Show branch name
        run: echo "The value of branch name is ${{ stpes.get-branch-name-of-pr }}"