name: Test of scheduled events

on:
  schedule:
    # FOR DEBUGGING, every 5 minutes of every day
    - cron: '*/5 * * * *' 
    # FOR DEBUGGING, every 47th minute of every hour of every day
    - cron: '47 * * * *' 

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '*/5 * * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
